import { createServer } from 'node:http';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright-core';
import { launch } from '../browser.mjs';
const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, '..', 'dist');
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' };
const server = createServer((req, res) => { const f = join(dist, (req.url ?? '/').split('?')[0].slice(1)); if (!existsSync(f)) { res.writeHead(404); return res.end(); } res.writeHead(200, { 'content-type': MIME[extname(f)] ?? 'application/octet-stream' }); res.end(readFileSync(f)); });
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const browser = await launch(chromium);
const page = await browser.newPage({ viewport: { width: 640, height: 720 } });
const appearance = process.env.A ?? 'light';
await page.goto(`http://127.0.0.1:${server.address().port}/reference.html?appearance=${appearance}&open=1`);
await page.waitForTimeout(900);
const fn = readFileSync(join(here, 'reference', 'probe.js'), 'utf8').replace(/^\/\/.*\n/, '');
const out = await page.evaluate(`(${fn})()`);
console.log(JSON.stringify(out, null, 1));
await browser.close(); server.close();
